baseURL: 'https://infinitylx.org/'
languageCode: en-us
title: Infinity's space
theme: manis-theme
builddrafts: false
canonifyurls: true
contentdir: content
layoutdir: layouts
publishdir: public
author: Vladyslav
pluralizelisttitles: false
Copyright: Copyright © 2012-2021 Infinitylx

permalinks:
  blog: 'blog/:slug/'

params:
  dateformat: 'Jan 2, 2006'
  dateFmt: 2 January 2006
  dateformfull: 'Mon January 2 2006 15:04:05 MST'
  description: 'Blog, Photos and Pet-projects.'
  copyright: Copyright © 2012-2021 Infinitylx
  logofile: img/logo.png
  faviconfile: img/logo.png
  licenseURL: /license
  highlightjs: true
  HighlightJsStyle: default
  progressively: true
  align_left: false
  lang: en
  defaultContentLanguage: en
  defaultContentLanguageInSubdir: false
  DebugCSS: false
  InterFont: true
  FiraCodeFont: true
  github: infinitylX
  email: infinity89@gmail.com
  twitter: infinitylX
  social_banner: img/banner.png
  posts_navigation: true
  small_banner_logo: false
  latestpostcount: 5
  usesmallsummarycard: true
  postSection: blog

